[package]
name = "local-file-storage"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gluesql = "0.14"
async-trait = "0.1"