[package]
name = "core"
authors = ["Seonghun <dev.seonghun@gmail.com>"]
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
local-file-storage.workspace = true
gluesql = "0.14"