name: Rust

on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_workspace:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read rust-toolchain file
        id: rust-toolchain
        run: echo "toolchain=$(cat rust-toolchain)" >> $GITHUB_OUTPUT
      - name: Add clippy
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.rust-toolchain.outputs.toolchain }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets -- -D warnings

  rust_fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read rust-toolchain file
        id: rust-toolchain
        run: echo "toolchain=$(cat rust-toolchain)" >> $GITHUB_OUTPUT
      - name: Add rustfmt
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.rust-toolchain.outputs.toolchain }}
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo fmt -- --check

  rust_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
